-- 0010_permission_matrix.sql · Etapa E2 (administración)
-- Matriz de permisos por módulo y rol (PRD 2.2): L = leer, C = crear/editar borrador, F = firmar,
-- A = aprobar. Los datos se generaron desde docs/PRD_GRUFARCOL.md con scripts/gen-permission-matrix.ts;
-- la prueba E2E compara la pantalla S-04 con el PRD. Es de solo lectura (se cambia por migración).
-- Las políticas RLS de las etapas siguientes consultan has_module_permission().

create table public.permission_modules (
  code text primary key,
  name text not null,
  order_no int not null unique,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create table public.module_permissions (
  id uuid primary key default gen_random_uuid(),
  module_code text not null references public.permission_modules (code),
  role public.app_role not null,
  cell_text text not null,
  can_read boolean not null,
  can_create boolean not null,
  can_sign boolean not null,
  can_approve boolean not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  unique (module_code, role)
);

comment on table public.module_permissions is
  'Matriz de permisos del PRD 2.2 (texto de la celda y banderas L/C/F/A). Solo lectura.';

alter table public.permission_modules enable row level security;
alter table public.module_permissions enable row level security;
select app_private.register_table('public.permission_modules', p_append_only => true);
select app_private.register_table('public.module_permissions', p_append_only => true);
create policy "authenticated can read permission modules" on public.permission_modules
  for select to authenticated using (true);
create policy "authenticated can read module permissions" on public.module_permissions
  for select to authenticated using (true);
revoke all on table public.permission_modules, public.module_permissions from anon;
revoke insert, update, delete, truncate on table public.permission_modules, public.module_permissions
  from authenticated;

insert into public.permission_modules (code, name, order_no) values
  ('brief', 'Brief', 1),
  ('formula_especificacion_instructivo', 'Fórmula / Especificación / Instructivo', 2),
  ('prototipos_estabilidad_y_costos', 'Prototipos, estabilidad y costos', 3),
  ('solicitudes_y_documentos_de_la_op', 'Solicitudes y documentos de la OP (PDF, rótulos, codificado)', 4),
  ('recepcion_inventario', 'Recepción / Inventario', 5),
  ('liberacion_de_insumos', 'Liberación de insumos', 6),
  ('orden_de_produccion', 'Orden de producción', 7),
  ('dispensacion_fabricacion_envase_acond', 'Dispensación / Fabricación / Envase / Acond.', 8),
  ('resultados_y_certificado_analitico', 'Resultados y certificado analítico', 9),
  ('desviaciones_capa', 'Desviaciones / CAPA', 10),
  ('liberacion_final_del_lote', 'Liberación final del lote', 11),
  ('paquete_tecnico', 'Paquete técnico (lista de verificación de expediente)', 12),
  ('trazabilidad_auditoria', 'Trazabilidad / Auditoría (consulta)', 13),
  ('usuarios_catalogos_perfiles', 'Usuarios, catálogos, perfiles', 14),
  ('plantillas_de_proceso', 'Plantillas de proceso (etapas y pasos: despeje de línea, dispensación, fabricación, envase, acondicionamiento y otras)', 15),
  ('bodegas_estantes_y_ubicaciones', 'Bodegas, estantes y ubicaciones', 16),
  ('traslados_y_envios_a_bodegas_externas', 'Traslados y envíos a bodegas externas', 17),
  ('sistema_de_gestion_documental', 'Sistema de gestión documental (SGD): solicitar, redactar, revisar, aprobar, codificar, publicar y anular documentos', 18),
  ('lectura_y_capacitacion', 'Lectura y capacitación (leer, presentar cuestionario y obtener constancia)', 19);

insert into public.module_permissions (module_code, role, cell_text, can_read, can_create, can_sign, can_approve) values
  ('brief', 'comercial', 'C F', false, true, true, false),
  ('brief', 'idi', 'L', true, false, false, false),
  ('brief', 'bodega_aux', '—', false, false, false, false),
  ('brief', 'bodega_jefe', '—', false, false, false, false),
  ('brief', 'prod_aux', '—', false, false, false, false),
  ('brief', 'prod_coord', 'L', true, false, false, false),
  ('brief', 'lab_aux', '—', false, false, false, false),
  ('brief', 'cc_jefe', 'L', true, false, false, false),
  ('brief', 'aq_dir', 'L', true, false, false, false),
  ('brief', 'dt', 'L A', true, false, false, true),
  ('brief', 'admin', '—', false, false, false, false),
  ('brief', 'master', 'L', true, false, false, false),
  ('brief', 'aq_doc', 'L', true, false, false, false),
  ('brief', 'gerencia', 'L', true, false, false, false),
  ('brief', 'auditor', 'L', true, false, false, false),
  ('formula_especificacion_instructivo', 'comercial', 'L', true, false, false, false),
  ('formula_especificacion_instructivo', 'idi', 'C F', false, true, true, false),
  ('formula_especificacion_instructivo', 'bodega_aux', '—', false, false, false, false),
  ('formula_especificacion_instructivo', 'bodega_jefe', '—', false, false, false, false),
  ('formula_especificacion_instructivo', 'prod_aux', 'L', true, false, false, false),
  ('formula_especificacion_instructivo', 'prod_coord', 'L', true, false, false, false),
  ('formula_especificacion_instructivo', 'lab_aux', 'L', true, false, false, false),
  ('formula_especificacion_instructivo', 'cc_jefe', 'L F', true, false, true, false),
  ('formula_especificacion_instructivo', 'aq_dir', 'L A', true, false, false, true),
  ('formula_especificacion_instructivo', 'dt', 'L A', true, false, false, true),
  ('formula_especificacion_instructivo', 'admin', '—', false, false, false, false),
  ('formula_especificacion_instructivo', 'master', 'C (versión en borrador)', false, true, false, false),
  ('formula_especificacion_instructivo', 'aq_doc', 'C (codifica y versiona)', false, true, false, false),
  ('formula_especificacion_instructivo', 'gerencia', 'L A', true, false, false, true),
  ('formula_especificacion_instructivo', 'auditor', 'L', true, false, false, false),
  ('prototipos_estabilidad_y_costos', 'comercial', 'L', true, false, false, false),
  ('prototipos_estabilidad_y_costos', 'idi', 'C F', false, true, true, false),
  ('prototipos_estabilidad_y_costos', 'bodega_aux', '—', false, false, false, false),
  ('prototipos_estabilidad_y_costos', 'bodega_jefe', '—', false, false, false, false),
  ('prototipos_estabilidad_y_costos', 'prod_aux', '—', false, false, false, false),
  ('prototipos_estabilidad_y_costos', 'prod_coord', 'L', true, false, false, false),
  ('prototipos_estabilidad_y_costos', 'lab_aux', 'C (ensayo)', false, true, false, false),
  ('prototipos_estabilidad_y_costos', 'cc_jefe', 'F', false, false, true, false),
  ('prototipos_estabilidad_y_costos', 'aq_dir', 'L', true, false, false, false),
  ('prototipos_estabilidad_y_costos', 'dt', 'L A', true, false, false, true),
  ('prototipos_estabilidad_y_costos', 'admin', '—', false, false, false, false),
  ('prototipos_estabilidad_y_costos', 'master', 'L', true, false, false, false),
  ('prototipos_estabilidad_y_costos', 'aq_doc', '—', false, false, false, false),
  ('prototipos_estabilidad_y_costos', 'gerencia', 'L A', true, false, false, true),
  ('prototipos_estabilidad_y_costos', 'auditor', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'comercial', '—', false, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'idi', '—', false, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'bodega_aux', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'bodega_jefe', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'prod_aux', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'prod_coord', 'C F', false, true, true, false),
  ('solicitudes_y_documentos_de_la_op', 'lab_aux', '—', false, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'cc_jefe', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'aq_dir', 'L A (numeración y revisión)', true, false, false, true),
  ('solicitudes_y_documentos_de_la_op', 'dt', 'A', false, false, false, true),
  ('solicitudes_y_documentos_de_la_op', 'admin', '—', false, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'master', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'aq_doc', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'gerencia', 'L', true, false, false, false),
  ('solicitudes_y_documentos_de_la_op', 'auditor', 'L', true, false, false, false),
  ('recepcion_inventario', 'comercial', '—', false, false, false, false),
  ('recepcion_inventario', 'idi', 'L', true, false, false, false),
  ('recepcion_inventario', 'bodega_aux', 'C F', false, true, true, false),
  ('recepcion_inventario', 'bodega_jefe', 'L A', true, false, false, true),
  ('recepcion_inventario', 'prod_aux', 'L', true, false, false, false),
  ('recepcion_inventario', 'prod_coord', 'L', true, false, false, false),
  ('recepcion_inventario', 'lab_aux', '—', false, false, false, false),
  ('recepcion_inventario', 'cc_jefe', 'L', true, false, false, false),
  ('recepcion_inventario', 'aq_dir', 'L', true, false, false, false),
  ('recepcion_inventario', 'dt', 'L', true, false, false, false),
  ('recepcion_inventario', 'admin', '—', false, false, false, false),
  ('recepcion_inventario', 'master', 'L', true, false, false, false),
  ('recepcion_inventario', 'aq_doc', '—', false, false, false, false),
  ('recepcion_inventario', 'gerencia', 'L', true, false, false, false),
  ('recepcion_inventario', 'auditor', 'L', true, false, false, false),
  ('liberacion_de_insumos', 'comercial', '—', false, false, false, false),
  ('liberacion_de_insumos', 'idi', '—', false, false, false, false),
  ('liberacion_de_insumos', 'bodega_aux', '—', false, false, false, false),
  ('liberacion_de_insumos', 'bodega_jefe', 'L', true, false, false, false),
  ('liberacion_de_insumos', 'prod_aux', '—', false, false, false, false),
  ('liberacion_de_insumos', 'prod_coord', '—', false, false, false, false),
  ('liberacion_de_insumos', 'lab_aux', 'C', false, true, false, false),
  ('liberacion_de_insumos', 'cc_jefe', 'F A', false, false, true, true),
  ('liberacion_de_insumos', 'aq_dir', 'L', true, false, false, false),
  ('liberacion_de_insumos', 'dt', 'L', true, false, false, false),
  ('liberacion_de_insumos', 'admin', '—', false, false, false, false),
  ('liberacion_de_insumos', 'master', 'L', true, false, false, false),
  ('liberacion_de_insumos', 'aq_doc', '—', false, false, false, false),
  ('liberacion_de_insumos', 'gerencia', 'L', true, false, false, false),
  ('liberacion_de_insumos', 'auditor', 'L', true, false, false, false),
  ('orden_de_produccion', 'comercial', '—', false, false, false, false),
  ('orden_de_produccion', 'idi', '—', false, false, false, false),
  ('orden_de_produccion', 'bodega_aux', '—', false, false, false, false),
  ('orden_de_produccion', 'bodega_jefe', '—', false, false, false, false),
  ('orden_de_produccion', 'prod_aux', 'L', true, false, false, false),
  ('orden_de_produccion', 'prod_coord', 'C F', false, true, true, false),
  ('orden_de_produccion', 'lab_aux', '—', false, false, false, false),
  ('orden_de_produccion', 'cc_jefe', 'L', true, false, false, false),
  ('orden_de_produccion', 'aq_dir', 'L', true, false, false, false),
  ('orden_de_produccion', 'dt', 'L', true, false, false, false),
  ('orden_de_produccion', 'admin', '—', false, false, false, false),
  ('orden_de_produccion', 'master', 'L', true, false, false, false),
  ('orden_de_produccion', 'aq_doc', 'L', true, false, false, false),
  ('orden_de_produccion', 'gerencia', 'L', true, false, false, false),
  ('orden_de_produccion', 'auditor', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'comercial', '—', false, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'idi', '—', false, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'bodega_aux', '—', false, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'bodega_jefe', '—', false, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'prod_aux', 'C F', false, true, true, false),
  ('dispensacion_fabricacion_envase_acond', 'prod_coord', 'F (verifica)', false, false, true, false),
  ('dispensacion_fabricacion_envase_acond', 'lab_aux', '—', false, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'cc_jefe', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'aq_dir', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'dt', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'admin', '—', false, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'master', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'aq_doc', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'gerencia', 'L', true, false, false, false),
  ('dispensacion_fabricacion_envase_acond', 'auditor', 'L', true, false, false, false),
  ('resultados_y_certificado_analitico', 'comercial', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'idi', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'bodega_aux', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'bodega_jefe', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'prod_aux', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'prod_coord', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'lab_aux', 'C F', false, true, true, false),
  ('resultados_y_certificado_analitico', 'cc_jefe', 'F A', false, false, true, true),
  ('resultados_y_certificado_analitico', 'aq_dir', 'L', true, false, false, false),
  ('resultados_y_certificado_analitico', 'dt', 'L', true, false, false, false),
  ('resultados_y_certificado_analitico', 'admin', '—', false, false, false, false),
  ('resultados_y_certificado_analitico', 'master', 'L', true, false, false, false),
  ('resultados_y_certificado_analitico', 'aq_doc', 'L', true, false, false, false),
  ('resultados_y_certificado_analitico', 'gerencia', 'L', true, false, false, false),
  ('resultados_y_certificado_analitico', 'auditor', 'L', true, false, false, false),
  ('desviaciones_capa', 'comercial', 'C', false, true, false, false),
  ('desviaciones_capa', 'idi', 'C', false, true, false, false),
  ('desviaciones_capa', 'bodega_aux', 'C', false, true, false, false),
  ('desviaciones_capa', 'bodega_jefe', 'C', false, true, false, false),
  ('desviaciones_capa', 'prod_aux', 'C', false, true, false, false),
  ('desviaciones_capa', 'prod_coord', 'C', false, true, false, false),
  ('desviaciones_capa', 'lab_aux', 'C', false, true, false, false),
  ('desviaciones_capa', 'cc_jefe', 'C F', false, true, true, false),
  ('desviaciones_capa', 'aq_dir', 'A', false, false, false, true),
  ('desviaciones_capa', 'dt', 'L A', true, false, false, true),
  ('desviaciones_capa', 'admin', '—', false, false, false, false),
  ('desviaciones_capa', 'master', 'C', false, true, false, false),
  ('desviaciones_capa', 'aq_doc', 'C', false, true, false, false),
  ('desviaciones_capa', 'gerencia', 'L', true, false, false, false),
  ('desviaciones_capa', 'auditor', 'L', true, false, false, false),
  ('liberacion_final_del_lote', 'comercial', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'idi', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'bodega_aux', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'bodega_jefe', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'prod_aux', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'prod_coord', 'L', true, false, false, false),
  ('liberacion_final_del_lote', 'lab_aux', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'cc_jefe', 'F (revisión calidad)', false, false, true, false),
  ('liberacion_final_del_lote', 'aq_dir', 'F (revisión expediente)', false, false, true, false),
  ('liberacion_final_del_lote', 'dt', 'F A (libera)', false, false, true, true),
  ('liberacion_final_del_lote', 'admin', '—', false, false, false, false),
  ('liberacion_final_del_lote', 'master', 'L', true, false, false, false),
  ('liberacion_final_del_lote', 'aq_doc', 'L', true, false, false, false),
  ('liberacion_final_del_lote', 'gerencia', 'L', true, false, false, false),
  ('liberacion_final_del_lote', 'auditor', 'L', true, false, false, false),
  ('paquete_tecnico', 'comercial', '—', false, false, false, false),
  ('paquete_tecnico', 'idi', '—', false, false, false, false),
  ('paquete_tecnico', 'bodega_aux', '—', false, false, false, false),
  ('paquete_tecnico', 'bodega_jefe', '—', false, false, false, false),
  ('paquete_tecnico', 'prod_aux', '—', false, false, false, false),
  ('paquete_tecnico', 'prod_coord', 'F (verifica)', false, false, true, false),
  ('paquete_tecnico', 'lab_aux', '—', false, false, false, false),
  ('paquete_tecnico', 'cc_jefe', '—', false, false, false, false),
  ('paquete_tecnico', 'aq_dir', 'F (revisa)', false, false, true, false),
  ('paquete_tecnico', 'dt', 'F A (aprueba)', false, false, true, true),
  ('paquete_tecnico', 'admin', '—', false, false, false, false),
  ('paquete_tecnico', 'master', 'L', true, false, false, false),
  ('paquete_tecnico', 'aq_doc', 'L', true, false, false, false),
  ('paquete_tecnico', 'gerencia', 'L', true, false, false, false),
  ('paquete_tecnico', 'auditor', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'comercial', '—', false, false, false, false),
  ('trazabilidad_auditoria', 'idi', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'bodega_aux', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'bodega_jefe', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'prod_aux', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'prod_coord', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'lab_aux', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'cc_jefe', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'aq_dir', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'dt', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'admin', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'master', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'aq_doc', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'gerencia', 'L', true, false, false, false),
  ('trazabilidad_auditoria', 'auditor', 'L', true, false, false, false),
  ('usuarios_catalogos_perfiles', 'comercial', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'idi', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'bodega_aux', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'bodega_jefe', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'prod_aux', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'prod_coord', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'lab_aux', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'cc_jefe', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'aq_dir', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'dt', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'admin', 'C', false, true, false, false),
  ('usuarios_catalogos_perfiles', 'master', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'aq_doc', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'gerencia', '—', false, false, false, false),
  ('usuarios_catalogos_perfiles', 'auditor', '—', false, false, false, false),
  ('plantillas_de_proceso', 'comercial', '—', false, false, false, false),
  ('plantillas_de_proceso', 'idi', 'L', true, false, false, false),
  ('plantillas_de_proceso', 'bodega_aux', '—', false, false, false, false),
  ('plantillas_de_proceso', 'bodega_jefe', '—', false, false, false, false),
  ('plantillas_de_proceso', 'prod_aux', 'L', true, false, false, false),
  ('plantillas_de_proceso', 'prod_coord', 'L', true, false, false, false),
  ('plantillas_de_proceso', 'lab_aux', '—', false, false, false, false),
  ('plantillas_de_proceso', 'cc_jefe', 'L', true, false, false, false),
  ('plantillas_de_proceso', 'aq_dir', 'A', false, false, false, true),
  ('plantillas_de_proceso', 'dt', 'A', false, false, false, true),
  ('plantillas_de_proceso', 'admin', '—', false, false, false, false),
  ('plantillas_de_proceso', 'master', 'C (versión en borrador)', false, true, false, false),
  ('plantillas_de_proceso', 'aq_doc', 'C (codifica)', false, true, false, false),
  ('plantillas_de_proceso', 'gerencia', 'L', true, false, false, false),
  ('plantillas_de_proceso', 'auditor', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'comercial', '—', false, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'idi', '—', false, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'bodega_aux', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'bodega_jefe', 'C F', false, true, true, false),
  ('bodegas_estantes_y_ubicaciones', 'prod_aux', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'prod_coord', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'lab_aux', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'cc_jefe', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'aq_dir', 'A (bodegas externas)', false, false, false, true),
  ('bodegas_estantes_y_ubicaciones', 'dt', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'admin', 'C', false, true, false, false),
  ('bodegas_estantes_y_ubicaciones', 'master', '—', false, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'aq_doc', '—', false, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'gerencia', 'L', true, false, false, false),
  ('bodegas_estantes_y_ubicaciones', 'auditor', 'L', true, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'comercial', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'idi', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'bodega_aux', 'C', false, true, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'bodega_jefe', 'C F A', false, true, true, true),
  ('traslados_y_envios_a_bodegas_externas', 'prod_aux', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'prod_coord', 'L', true, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'lab_aux', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'cc_jefe', 'L', true, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'aq_dir', 'L', true, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'dt', 'L', true, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'admin', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'master', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'aq_doc', '—', false, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'gerencia', 'L', true, false, false, false),
  ('traslados_y_envios_a_bodegas_externas', 'auditor', 'L', true, false, false, false),
  ('sistema_de_gestion_documental', 'comercial', 'C (autor)', false, true, false, false),
  ('sistema_de_gestion_documental', 'idi', 'C (autor)', false, true, false, false),
  ('sistema_de_gestion_documental', 'bodega_aux', 'C (autor)', false, true, false, false),
  ('sistema_de_gestion_documental', 'bodega_jefe', 'C (autor) F (revisa a su equipo)', false, true, true, false),
  ('sistema_de_gestion_documental', 'prod_aux', 'C (autor)', false, true, false, false),
  ('sistema_de_gestion_documental', 'prod_coord', 'C (autor) F (revisa a su equipo)', false, true, true, false),
  ('sistema_de_gestion_documental', 'lab_aux', 'C (autor)', false, true, false, false),
  ('sistema_de_gestion_documental', 'cc_jefe', 'C (autor) F (revisa)', false, true, true, false),
  ('sistema_de_gestion_documental', 'aq_dir', 'F A (revisa, aprueba y decide anulaciones)', false, false, true, true),
  ('sistema_de_gestion_documental', 'dt', 'A (documentos técnicos y administrativos)', false, false, false, true),
  ('sistema_de_gestion_documental', 'admin', '—', false, false, false, false),
  ('sistema_de_gestion_documental', 'master', 'C (autor)', false, true, false, false),
  ('sistema_de_gestion_documental', 'aq_doc', 'C F (estandariza, codifica, publica y custodia)', false, true, true, false),
  ('sistema_de_gestion_documental', 'gerencia', 'A (documentos administrativos)', false, false, false, true),
  ('sistema_de_gestion_documental', 'auditor', 'L', true, false, false, false),
  ('lectura_y_capacitacion', 'comercial', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'idi', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'bodega_aux', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'bodega_jefe', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'prod_aux', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'prod_coord', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'lab_aux', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'cc_jefe', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'aq_dir', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'dt', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'admin', '—', false, false, false, false),
  ('lectura_y_capacitacion', 'master', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'aq_doc', 'C (asigna y hace seguimiento)', false, true, false, false),
  ('lectura_y_capacitacion', 'gerencia', 'F (lee)', false, false, true, false),
  ('lectura_y_capacitacion', 'auditor', 'L', true, false, false, false);

-- ¿El usuario actual tiene el permiso en el módulo? (read, create, sign, approve)
create or replace function public.has_module_permission(p_module text, p_permission text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.module_permissions mp
    where mp.module_code = p_module
      and mp.role = any(public.current_user_roles())
      and case p_permission
            when 'read' then mp.can_read or mp.can_create or mp.can_sign or mp.can_approve
            when 'create' then mp.can_create
            when 'sign' then mp.can_sign
            when 'approve' then mp.can_approve
            else false
          end
  );
$$;

revoke execute on function public.has_module_permission(text, text) from public, anon;
grant execute on function public.has_module_permission(text, text) to authenticated;
